import { Router } from "express";
import authRoutes from "./auth.routes";
import usersRoutes from "./users.routes";
import rolesRoutes from "./roles.routes";
import coursesRoutes from "./courses.routes";
import cohortsRoutes from "./cohorts.routes";
import categoriesRoutes from "./categories.routes";
import tagsRoutes from "./tags.routes";
import certificateTemplatesRoutes from "./certificate-templates.routes";
import courseCertificatesRoutes from "./course-certificates.routes";
import enrollmentsRoutes from "./enrollments.routes";
import notificationPreferencesRoutes from "./notification-preferences.routes";
import settingsRoutes from "./settings.routes";
import modulesRoutes from "./modules.routes";
import lessonsRoutes from "./lessons.routes";
import resourcesRoutes from "./resources.routes";
import assessmentsRoutes from "./assessments.routes";
import assignmentsRoutes from "./assignments.routes";
import discussionsRoutes from "./discussions.routes";
import communityRoutes from "./community.routes";
import announcementsRoutes from "./announcements.routes";
import reportsRoutes from "./reports.routes";
import searchRoutes from "./search.routes";
import planSettingsRoutes from "./plan-settings.routes";
import meRoutes from "./me.routes";
import certificatesRoutes from "./certificates.routes";
import leaderboardRoutes from "./leaderboard.routes";
import notificationsRoutes from "./notifications.routes";
import chatRoutes from "./chat.routes";
import uploadsRoutes from "./uploads.routes";
import liveAccountsRoutes from "./live-accounts.routes";
import filesRoutes from "./files.routes";
import storageSettingsRoutes from "./storage-settings.routes";
import zohoSettingsRoutes from "./zoho-settings.routes";
import bookingsRoutes from "./bookings.routes";
import groupCallsRoutes from "./group-calls.routes";
import mentorRatingsRoutes from "./mentor-ratings.routes";
import callsRoutes from "./calls.routes";
import sseRoutes from "./sse.routes";
import storageRoutes from "./storage.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", usersRoutes);
router.use("/roles", rolesRoutes);
router.use("/courses", coursesRoutes);
router.use("/cohorts", cohortsRoutes);
router.use("/categories", categoriesRoutes);
router.use("/tags", tagsRoutes);
router.use("/certificate-templates", certificateTemplatesRoutes);
router.use("/course-certificates", courseCertificatesRoutes);
router.use("/enrollments", enrollmentsRoutes);
router.use("/notification-preferences", notificationPreferencesRoutes);
router.use("/settings", settingsRoutes);
router.use("/modules", modulesRoutes);
router.use("/lessons", lessonsRoutes);
router.use("/resources", resourcesRoutes);
router.use("/assessments", assessmentsRoutes);
router.use("/assignments", assignmentsRoutes);
router.use("/discussions", discussionsRoutes);
router.use("/communities", communityRoutes);
router.use("/announcements", announcementsRoutes);
router.use("/reports", reportsRoutes);
router.use("/search", searchRoutes);
router.use("/plan-settings", planSettingsRoutes);
router.use("/me", meRoutes);
router.use("/certificates", certificatesRoutes);
router.use("/leaderboard", leaderboardRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/chat", chatRoutes);
router.use("/uploads", uploadsRoutes);
router.use("/live-accounts", liveAccountsRoutes);
router.use("/files", filesRoutes);
router.use("/storage-settings", storageSettingsRoutes);
router.use("/zoho-settings", zohoSettingsRoutes);
router.use("/bookings", bookingsRoutes);
router.use("/group-calls", groupCallsRoutes);
router.use("/mentor-ratings", mentorRatingsRoutes);
router.use("/calls", callsRoutes);
router.use("/events", sseRoutes);
router.use("/storage", storageRoutes);

export default router;
